// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANptOIdffcHSi-PWwZuymeE1eMBD2ausY',
    appId: '1:199892168047:web:abd3de2708633da2f64c9a',
    messagingSenderId: '199892168047',
    projectId: 'testapp-410707',
    authDomain: 'testapp-410707.firebaseapp.com',
    databaseURL: 'https://testapp-410707-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testapp-410707.appspot.com',
    measurementId: 'G-40G3B56055',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP4wPwlWgY87yesPSTFurxr73LmrrYGaA',
    appId: '1:199892168047:android:1ca215495715db34f64c9a',
    messagingSenderId: '199892168047',
    projectId: 'testapp-410707',
    databaseURL: 'https://testapp-410707-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testapp-410707.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4PDwlbjmksTkO3ScodsMV9QetbnrHcbs',
    appId: '1:199892168047:ios:85cff7f2ff82895ef64c9a',
    messagingSenderId: '199892168047',
    projectId: 'testapp-410707',
    databaseURL: 'https://testapp-410707-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testapp-410707.appspot.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4PDwlbjmksTkO3ScodsMV9QetbnrHcbs',
    appId: '1:199892168047:ios:145a433c9129a910f64c9a',
    messagingSenderId: '199892168047',
    projectId: 'testapp-410707',
    databaseURL: 'https://testapp-410707-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testapp-410707.appspot.com',
    iosBundleId: 'com.example.loginPage.RunnerTests',
  );
}
